runtime: python37
service: xestore

env_variables:
  XESTORE_DOMAIN: pmts.xenonnt.org
  XESTORE_MONGO_HOST: "lngs-proxy.yossisprojects.com"
  XESTORE_MONGO_PORT: 27017
  XESTORE_MONGO_DB: pmts
  XESTORE_MONGO_USER: api
  XESTORE_MONGO_AUTH_SOURCE: pmts
  #XESTORE_MONGO_REPLICA_SET: RunsDatabase
  #XESTORE_ENDPOINT_DIR: endpoints
